import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/componant/Navbar";
import Footer from "@/componant/footer";
import "bootstrap-icons/font/bootstrap-icons.css";
import{Heebo} from "next/font/google";

const heebo = Heebo({subsets:["latin"], 
weight: ["400", "700"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={heebo.className}>
        <Navbar/>
        {children}
      <Footer/>
      </body>
    </html>
  );
}
